/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package org.avro.request;
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum Active {
  YES, NO  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"Active\",\"namespace\":\"org.avro.request\",\"symbols\":[\"YES\",\"NO\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
